-- Security layer for the foundation tables.
--
-- FR-PLT-03 requires a table's RLS policies to exist in the same migration as the table.
-- 0000 is machine-generated by drizzle-kit and is regenerated on schema change, so the
-- policies live here and `drizzle-kit generate` is never run without applying this file
-- immediately after. The CI test `rls-coverage.spec.ts` fails if any table carrying
-- `clinic_id` lacks a policy, which is the enforcement that actually holds.

--> statement-breakpoint
CREATE EXTENSION IF NOT EXISTS pgcrypto;
--> statement-breakpoint
CREATE EXTENSION IF NOT EXISTS btree_gist;
--> statement-breakpoint
CREATE EXTENSION IF NOT EXISTS pg_trgm;

--> statement-breakpoint
-- ---------------------------------------------------------------------------
-- Request context
--
-- Set per transaction with set_config(..., true). The third argument is the
-- difference between safe and catastrophic: a session-level setting leaks to the
-- next request that borrows the same pooled connection (PRD §15.4).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION app_current_clinic_id() RETURNS uuid
  LANGUAGE sql STABLE
  SET search_path = pg_catalog, public
AS $$ SELECT nullif(current_setting('app.clinic_id', true), '')::uuid $$;

--> statement-breakpoint
CREATE OR REPLACE FUNCTION app_current_user_id() RETURNS uuid
  LANGUAGE sql STABLE
  SET search_path = pg_catalog, public
AS $$ SELECT nullif(current_setting('app.user_id', true), '')::uuid $$;

--> statement-breakpoint
-- ---------------------------------------------------------------------------
-- Cross-reference guards (FR-PLT-05)
--
-- SECURITY DEFINER is load-bearing. RLS confirms a row's own clinic_id; it says
-- nothing about whether the *referenced* row belongs to another clinic. Without
-- DEFINER the lookup below reads a row RLS exists to hide, returns NULL, the
-- comparison evaluates to NULL rather than true, and the guard admits exactly the
-- row it was written to reject. Invisible if tests run as superuser.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION guard_membership_branch() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER
  SET search_path = pg_catalog, public
AS $$
DECLARE v_clinic uuid;
BEGIN
  IF new.branch_id IS NULL THEN
    RETURN new;
  END IF;
  SELECT b.clinic_id INTO v_clinic FROM branches b WHERE b.id = new.branch_id;
  IF v_clinic IS NULL OR v_clinic <> new.clinic_id THEN
    RAISE EXCEPTION 'branch % does not belong to clinic %', new.branch_id, new.clinic_id
      USING ERRCODE = '42501';
  END IF;
  RETURN new;
END $$;

--> statement-breakpoint
CREATE TRIGGER memberships_guard_branch
  BEFORE INSERT OR UPDATE ON memberships
  FOR EACH ROW EXECUTE FUNCTION guard_membership_branch();

--> statement-breakpoint
-- ---------------------------------------------------------------------------
-- FR-IAM-08 — a clinic always retains at least one owner.
--
-- The check is inside the write, under a row lock, not a count followed by an
-- update. Two concurrent demotions must leave exactly one owner standing.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION guard_last_owner() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER
  SET search_path = pg_catalog, public
AS $$
DECLARE v_remaining integer;
BEGIN
  IF old.role = 'owner'
     AND (new.revoked_at IS NOT NULL OR new.role <> 'owner')
     AND old.revoked_at IS NULL
  THEN
    PERFORM 1 FROM memberships m
      WHERE m.clinic_id = old.clinic_id
        AND m.role = 'owner'
        AND m.revoked_at IS NULL
        AND m.id <> old.id
      FOR UPDATE;
    GET DIAGNOSTICS v_remaining = ROW_COUNT;
    IF v_remaining = 0 THEN
      RAISE EXCEPTION 'a clinic must retain at least one owner'
        USING ERRCODE = '23514';
    END IF;
  END IF;
  RETURN new;
END $$;

--> statement-breakpoint
CREATE TRIGGER memberships_guard_last_owner
  BEFORE UPDATE ON memberships
  FOR EACH ROW EXECUTE FUNCTION guard_last_owner();

--> statement-breakpoint
-- ---------------------------------------------------------------------------
-- FR-PLT-07 — an expired subscription is read-only, never a lockout.
--
-- Enforced in the database. A check in the application is one missed branch away
-- from a write (review F15).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION assert_tenant_writable() RETURNS trigger
  LANGUAGE plpgsql SECURITY DEFINER
  SET search_path = pg_catalog, public
AS $$
DECLARE v_status subscription_status;
BEGIN
  SELECT s.status INTO v_status
    FROM subscriptions s
   WHERE s.clinic_id = new.clinic_id
   ORDER BY s.created_at DESC
   LIMIT 1;

  IF v_status IN ('expired', 'cancelled') THEN
    RAISE EXCEPTION 'clinic % is read-only: subscription is %', new.clinic_id, v_status
      USING ERRCODE = '55006';
  END IF;
  RETURN new;
END $$;

--> statement-breakpoint
CREATE TRIGGER branches_assert_writable
  BEFORE INSERT OR UPDATE ON branches
  FOR EACH ROW EXECUTE FUNCTION assert_tenant_writable();

--> statement-breakpoint
CREATE TRIGGER memberships_assert_writable
  BEFORE INSERT OR UPDATE ON memberships
  FOR EACH ROW EXECUTE FUNCTION assert_tenant_writable();

--> statement-breakpoint
CREATE TRIGGER therapists_assert_writable
  BEFORE INSERT OR UPDATE ON therapists
  FOR EACH ROW EXECUTE FUNCTION assert_tenant_writable();

--> statement-breakpoint
-- ---------------------------------------------------------------------------
-- Pre-authentication lookups.
--
-- Login happens before any tenant context exists, so these are the only read
-- paths that may run without one. Each is SECURITY DEFINER, takes no actor
-- argument it could be lied to about, and returns the minimum needed.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION auth_find_user_by_identifier(p_identifier text)
  RETURNS TABLE (id uuid, password_hash text, is_active boolean, full_name text)
  LANGUAGE sql SECURITY DEFINER STABLE
  SET search_path = pg_catalog, public
AS $$
  SELECT u.id, u.password_hash, u.is_active, u.full_name
    FROM users u
   WHERE u.email = lower(p_identifier) OR u.phone = p_identifier
   LIMIT 1
$$;

--> statement-breakpoint
CREATE OR REPLACE FUNCTION auth_find_refresh_token(p_token_hash text)
  RETURNS TABLE (
    id uuid, user_id uuid, family_id uuid, clinic_id uuid,
    expires_at timestamptz, used_at timestamptz, revoked_at timestamptz
  )
  LANGUAGE sql SECURITY DEFINER STABLE
  SET search_path = pg_catalog, public
AS $$
  SELECT r.id, r.user_id, r.family_id, r.clinic_id,
         r.expires_at, r.used_at, r.revoked_at
    FROM refresh_tokens r
   WHERE r.token_hash = p_token_hash
   LIMIT 1
$$;

--> statement-breakpoint
-- Reuse detection: presenting an already-used token revokes the whole family
-- (FR-IAM-02). Definer because the caller has no tenant context yet.
CREATE OR REPLACE FUNCTION auth_revoke_token_family(p_family_id uuid)
  RETURNS integer
  LANGUAGE plpgsql SECURITY DEFINER
  SET search_path = pg_catalog, public
AS $$
DECLARE v_count integer;
BEGIN
  UPDATE refresh_tokens
     SET revoked_at = now()
   WHERE family_id = p_family_id AND revoked_at IS NULL;
  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END $$;

--> statement-breakpoint
-- ---------------------------------------------------------------------------
-- Row-level security
--
-- FORCE so the policy applies to the table owner too. Helper calls are wrapped in
-- (select ...) so the planner evaluates them once per query rather than once per
-- row (NFR-PRF-07).
-- ---------------------------------------------------------------------------
ALTER TABLE clinics        ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE clinics        FORCE  ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE subscriptions  ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE subscriptions  FORCE  ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE branches       ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE branches       FORCE  ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE memberships    ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE memberships    FORCE  ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE therapists     ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE therapists     FORCE  ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE users          ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE users          FORCE  ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE refresh_tokens ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE refresh_tokens FORCE  ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE plans          ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE plans          FORCE  ROW LEVEL SECURITY;

--> statement-breakpoint
-- A user may read the clinics they hold an active membership in, so that login can
-- offer the choice before any clinic context exists. Own memberships only.
CREATE POLICY clinics_read ON clinics FOR SELECT
  USING (
    id = (SELECT app_current_clinic_id())
    OR EXISTS (
      SELECT 1 FROM memberships m
       WHERE m.clinic_id = clinics.id
         AND m.user_id = (SELECT app_current_user_id())
         AND m.revoked_at IS NULL
    )
  );
--> statement-breakpoint
CREATE POLICY clinics_write ON clinics FOR UPDATE
  USING (id = (SELECT app_current_clinic_id()))
  WITH CHECK (id = (SELECT app_current_clinic_id()));

--> statement-breakpoint
-- Plans are platform reference data: readable by anyone, writable by no one
-- through the application role.
CREATE POLICY plans_read ON plans FOR SELECT USING (true);

--> statement-breakpoint
CREATE POLICY subscriptions_read ON subscriptions FOR SELECT
  USING (clinic_id = (SELECT app_current_clinic_id()));

--> statement-breakpoint
CREATE POLICY branches_read ON branches FOR SELECT
  USING (clinic_id = (SELECT app_current_clinic_id()));
--> statement-breakpoint
CREATE POLICY branches_insert ON branches FOR INSERT
  WITH CHECK (clinic_id = (SELECT app_current_clinic_id()));
--> statement-breakpoint
CREATE POLICY branches_update ON branches FOR UPDATE
  USING (clinic_id = (SELECT app_current_clinic_id()))
  WITH CHECK (clinic_id = (SELECT app_current_clinic_id()));

--> statement-breakpoint
-- A user may read their own memberships without a clinic context, so that login
-- can offer the list of clinics they belong to. Own rows only.
CREATE POLICY memberships_read ON memberships FOR SELECT
  USING (
    clinic_id = (SELECT app_current_clinic_id())
    OR user_id = (SELECT app_current_user_id())
  );
--> statement-breakpoint
CREATE POLICY memberships_insert ON memberships FOR INSERT
  WITH CHECK (clinic_id = (SELECT app_current_clinic_id()));
--> statement-breakpoint
CREATE POLICY memberships_update ON memberships FOR UPDATE
  USING (clinic_id = (SELECT app_current_clinic_id()))
  WITH CHECK (clinic_id = (SELECT app_current_clinic_id()));

--> statement-breakpoint
CREATE POLICY therapists_read ON therapists FOR SELECT
  USING (clinic_id = (SELECT app_current_clinic_id()));
--> statement-breakpoint
CREATE POLICY therapists_insert ON therapists FOR INSERT
  WITH CHECK (clinic_id = (SELECT app_current_clinic_id()));
--> statement-breakpoint
CREATE POLICY therapists_update ON therapists FOR UPDATE
  USING (clinic_id = (SELECT app_current_clinic_id()))
  WITH CHECK (clinic_id = (SELECT app_current_clinic_id()));

--> statement-breakpoint
-- A staff user sees themselves, and colleagues who share the current clinic.
-- Never the whole users table.
CREATE POLICY users_read ON users FOR SELECT
  USING (
    id = (SELECT app_current_user_id())
    OR EXISTS (
      SELECT 1 FROM memberships m
       WHERE m.user_id = users.id
         AND m.clinic_id = (SELECT app_current_clinic_id())
         AND m.revoked_at IS NULL
    )
  );
--> statement-breakpoint
CREATE POLICY users_update_self ON users FOR UPDATE
  USING (id = (SELECT app_current_user_id()))
  WITH CHECK (id = (SELECT app_current_user_id()));

--> statement-breakpoint
CREATE POLICY refresh_tokens_own ON refresh_tokens FOR SELECT
  USING (user_id = (SELECT app_current_user_id()));
--> statement-breakpoint
CREATE POLICY refresh_tokens_insert ON refresh_tokens FOR INSERT
  WITH CHECK (user_id = (SELECT app_current_user_id()));
--> statement-breakpoint
CREATE POLICY refresh_tokens_update ON refresh_tokens FOR UPDATE
  USING (user_id = (SELECT app_current_user_id()))
  WITH CHECK (user_id = (SELECT app_current_user_id()));

--> statement-breakpoint
-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX branches_clinic_idx      ON branches (clinic_id);
--> statement-breakpoint
CREATE INDEX memberships_clinic_idx   ON memberships (clinic_id);
--> statement-breakpoint
CREATE INDEX memberships_user_idx     ON memberships (user_id);
--> statement-breakpoint
CREATE INDEX therapists_clinic_idx    ON therapists (clinic_id);
--> statement-breakpoint
CREATE INDEX subscriptions_clinic_idx ON subscriptions (clinic_id);
--> statement-breakpoint
CREATE INDEX refresh_tokens_family_idx ON refresh_tokens (family_id);
--> statement-breakpoint
CREATE UNIQUE INDEX memberships_active_unique
  ON memberships (clinic_id, user_id, role) WHERE revoked_at IS NULL;

--> statement-breakpoint
-- ---------------------------------------------------------------------------
-- Privileges (NFR-SEC-09)
--
-- Immutability is enforced at privilege level, not by policy alone. A missing
-- policy is a silent grant in some configurations; a revoked privilege fails
-- loudly and cannot be reintroduced by a migration that forgot a policy.
--
-- No DELETE is granted on any table, ever. Every table therefore needs a
-- soft-void path — `memberships.revoked_at` is the pattern.
--
-- ALTER DEFAULT PRIVILEGES is deliberately NOT used: each future migration must
-- state its own grants, so that adding an append-only table is a decision rather
-- than an inheritance.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'physioflow_app') THEN
    -- Production creates the role with its password out of band; this branch only
    -- guarantees the grants below have a subject.
    CREATE ROLE physioflow_app NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
  END IF;
END $$;

--> statement-breakpoint
GRANT USAGE ON SCHEMA public TO physioflow_app;
--> statement-breakpoint
GRANT SELECT, INSERT, UPDATE ON
  clinics, subscriptions, branches, memberships, therapists, users, refresh_tokens
  TO physioflow_app;
--> statement-breakpoint
GRANT SELECT ON plans TO physioflow_app;
--> statement-breakpoint
REVOKE DELETE ON ALL TABLES IN SCHEMA public FROM physioflow_app;
--> statement-breakpoint
GRANT EXECUTE ON FUNCTION
  app_current_clinic_id(),
  app_current_user_id(),
  auth_find_user_by_identifier(text),
  auth_find_refresh_token(text),
  auth_revoke_token_family(uuid)
  TO physioflow_app;
