// One flat string table. English is the default; Arabic is kept as a real
// locale rather than deleted, so switching back is a constant change and not
// a rewrite. No i18n library — this is ~150 lines and a library would be
// more code than the thing it replaces.
//
// Locale comes from the environment rather than a hardcoded constant, so
// flipping the whole UI to Arabic is a deploy setting and not a code change.
// NEXT_PUBLIC_ because client components render strings too — a locale is
// not a secret. When per-clinic locale lands, read it from the clinic row
// and thread it through instead.
const RAW = process.env.NEXT_PUBLIC_LOCALE;
export const LOCALE: "en" | "ar" = RAW === "ar" ? "ar" : "en";

export const DIR = LOCALE === "ar" ? "rtl" : "ltr";
export const HTML_LANG = LOCALE;

const en = {
  appName: "Clinic OS",
  appTagline: "Physiotherapy clinic management",

  // auth
  signInTitle: "Clinic OS",
  signInSubtitle: "Sign in to see your clinic's day",
  email: "Email",
  password: "Password",
  signIn: "Sign in",
  badCredentials: "That email and password don't match",
  signOut: "Sign out",

  // shell
  receptionDay: "Reception",
  searchTheDay: "Search the day",
  liveUpdating: "Live",
  darkMode: "Dark mode",
  lightMode: "Light mode",
  notInAnyClinic:
    "This account isn't linked to a clinic yet. Ask the owner to add you.",
  mustSignIn: "You need to sign in first.",

  // roles
  roleOwner: "Owner",
  roleReception: "Reception",
  roleTherapist: "Therapist",
  roleAccountant: "Accountant",
  rolePlatformAdmin: "Platform admin",

  // summary strip
  waiting: "Waiting",
  ofAppointmentsToday: "of {n} today",
  finished: "Finished",
  noShows: "no-shows",
  owedByPatients: "Owed by patients",
  acrossNPatients: "across {n} patients",

  // bands
  bandWaiting: "Waiting",
  bandDone: "Done",
  queueEmpty: "Nobody waiting — the queue is clear",
  noSearchResults: "No one matches that search",
  nobodyFinishedYet: "Nobody has finished yet today",
  filterPlaceholder: "Filter by name or phone",
  addWalkIn: "+ Walk-in",

  // row
  arrived: "Arrived",
  noShow: "No-show",
  didNotAttend: "No-show",
  takePayment: "Take payment",
  refund: "Refund",
  onTime: "On time",
  waitingMinutes: "waiting {n}m",
  dueInMinutes: "in {n}m",
  owesAmount: "owes {amount}",
  missesRate: "misses {n}% of appointments",

  // payment sheet
  paymentTitle: "Take payment",
  due: "due",
  packageOptional: "Package (optional)",
  noPackageSingleSession: "No package — single session",
  packageOf: "Package of {n}",
  sessionsLeft: "{n} left",
  paymentGoesToPackage:
    "This goes against the package, not today's session.",
  method: "Method",
  amount: "Amount",
  cash: "Cash",
  card: "Card",
  wallet: "Mobile wallet",
  addAnotherMethod: "+ Split across another method",
  removeMethod: "Remove this method",
  total: "Total",
  cancel: "Cancel",
  take: "Take",
  enterAnAmount: "Enter an amount above zero",

  // refund sheet
  refundTitle: "Refund",
  payment: "Payment",
  refundAmount: "Amount to refund",
  reason: "Reason",
  reasonPlaceholder: "e.g. session cancelled after payment",
  refundIt: "Refund",
  noPaymentsYet: "No payments recorded for this patient",
  maxRefundableBefore: "At most",
  maxRefundableAfter:
    ". The database itself rejects a refund larger than the payment.",
  pickAPayment: "Pick the payment to refund",
  amountAboveZero: "The amount must be above zero",
  reasonRequired: "Write a reason — it goes on the record",

  // walk-in sheet
  walkInTitle: "Walk-in",
  walkInSubtitle: "Booked from right now",
  existingPatient: "Existing patient?",
  searchByNameOrPhone: "Search by name or phone",
  orNewPatient: "Or a new patient",
  name: "Name",
  phone: "Phone",
  change: "Change",
  consentLabel:
    "The patient consents to their health data being processed. Required by law — health data is sensitive under Egypt's Law 151/2020.",
  therapist: "Therapist",
  noTherapists: "No therapists yet",
  sessionMinutes: "Session length (minutes)",
  underPackage: "Under a package?",
  noSingleSession: "No — single session",
  addToQueue: "Add to queue",
  pickPatientOrEnterNew:
    "Pick an existing patient, or enter a name and phone",
  consentRequired: "The patient must consent to their health data being processed",
  pickTherapist: "Pick a therapist",
  durationAboveZero: "Session length must be above zero",
  therapistBusy: "That therapist is already booked at this time",

  // money rail
  leakingTitle: "Money left on the table",
  leakingSubtitle: "Sessions delivered that nobody paid for",
  nothingLeaking: "Every session is paid for.",
  sessionOn: "Session {date}",
  totalOwed: "Total owed",
  stalePackagesTitle: "Stalled packages",
  stalePackagesSubtitle:
    "Paid for, sessions not being used — the earliest sign a patient is drifting away",
  lastSessionOn: "Last session {date} · {n} left",
  notStartedYet: "not started",

  // platform admin
  adminTitle: "Platform",
  adminSubtitle: "Every clinic on this deployment",
  adminForbidden:
    "This account isn't a platform admin. Nothing here is available to it.",
  adminNotConfigured:
    "No platform admins are configured. Set PLATFORM_ADMIN_EMAILS in the server environment.",
  clinics: "Clinics",
  staff: "Staff",
  patients: "Patients",
  appointments: "Appointments",
  collected: "Collected",
  outstanding: "Outstanding",
  refunded: "Refunded",
  clinicName: "Clinic",
  activity: "Who did what",
  activitySubtitle: "Newest first, across every clinic",
  noActivity: "Nothing has happened yet",
  actionTookPayment: "took a payment of {amount}",
  actionRefunded: "refunded {amount}",
  actionRegisteredPatient: "registered a patient",
  actionBookedAppointment: "booked an appointment",
  actionSoldPackage: "sold a package of {n} sessions",
  phiNotice:
    "Patient names and clinical notes are deliberately not shown here. A platform admin sees how the business is running, not who is being treated for what — see DESIGN.md and SPEC.md for why.",
  backToClinic: "Back to the clinic",
  unknownUser: "unknown",
  noClinics: "No clinics yet",
  // schedule
  schedule: "Schedule",
  scheduleSubtitle: "Book ahead, move, cancel",
  weekOf: "Week of {date}",
  today: "Today",
  prevWeek: "Previous week",
  nextWeek: "Next week",
  allTherapists: "All therapists",
  book: "Book",
  bookSession: "Book a session",
  bookPlanOfCare: "Book a plan of care",
  oneSession: "One session",
  planOfCare: "Plan of care",
  date: "Date",
  time: "Time",
  sessions: "Sessions",
  repeatOn: "Repeat on",
  pricePerSession: "Price per session",
  priceHint: "Left at zero for a session covered by a package.",
  checkSlots: "Check the slots",
  slotsClear: "All {n} slots are free",
  slotsClash: "{n} of {total} slots clash",
  clashesWith: "clashes with {name}",
  clashesWithSomeone: "clashes with another booking",
  bookAnyway: "Book the {n} that are free",
  bookAll: "Book {n} sessions",
  booked: "Booked",
  bookedNOfM: "Booked {n} of {total}",
  noneBooked: "Nothing was booked",
  moveTo: "Move to",
  moveIt: "Move",
  cancelSession: "Cancel this session",
  cancelIt: "Cancel the session",
  cancelWarning:
    "The slot is freed and, if the session was already marked attended, the package credit goes back.",
  cancelled: "Cancelled",
  attended: "Attended",
  bookedStatus: "Booked",
  nothingThisWeek: "Nothing booked this week",
  noPatientPicked: "Pick a patient first",
  badDateOrTime: "That date or time isn't valid",
  tooManySessions: "A plan of care can hold at most 60 sessions",
  pickWeekdays: "Pick at least one day of the week to repeat on",
  sat: "Sat",
  sun: "Sun",
  mon: "Mon",
  tue: "Tue",
  wed: "Wed",
  thu: "Thu",
  fri: "Fri",
  // patient record
  patientRecord: "Patient",
  backToReception: "Back to today",
  registered: "Registered",
  consentOn: "Consent recorded {date}",
  consentMissing: "No consent recorded",
  consentMissingWhy:
    "Health data is sensitive under Egypt's Law 151/2020. Record consent before adding clinical information.",
  lastSeen: "Last seen",
  neverSeen: "Never attended",
  totalSessions: "Sessions attended",
  missedSessions: "Missed",
  lifetimeValue: "Paid to date",
  currentlyOwes: "Currently owes",
  packagesHeading: "Packages",
  noPackages: "No packages",
  packageProgress: "{used} of {total} used",
  expiredOn: "Expired {date}",
  expiresOn: "Expires {date}",
  paidOff: "Paid in full",
  stillOwing: "{amount} still owing",
  historyHeading: "Visit history",
  noHistory: "No visits yet",
  paymentsHeading: "Payments",
  noPaymentsRecorded: "No payments",
  upcomingHeading: "Upcoming",
  noUpcoming: "Nothing booked",
  patientNotFound: "No such patient in this clinic",
  viewRecord: "Open record",
  // patient search
  findPatient: "Find a patient",
  findPatientHint: "Search the whole clinic, not just today",
  searchResults: "{n} found",
  noMatches: "Nobody matches that",
  typeToSearch: "Type a name or phone number",
  owes: "owes",
  progress: "Progress",
  percentOf: "{value} of {max}",
  // owner home / finance
  finance: "Money",
  financeSubtitle: "What you earned, what you are owed, what you owe in treatment",
  leakHeadline: "{n} sessions delivered with no payment",
  leakNone: "Every session delivered has been paid for.",
  leakTotal: "Not collected",
  chaseIt: "Chase",
  earned: "Earned",
  earnedHint: "Treatment actually delivered",
  deferred: "Held for treatment owed",
  deferredHint: "Paid for, not yet delivered — this is a liability, not profit",
  receivable: "Owed to you",
  receivableHint: "Delivered and unpaid",
  collectedCash: "Cash collected",
  collectedHint: "What reached the till, net of refunds",
  ofCashIsNotYours: "{pct}% of your cash is not yours to spend yet",
  liabilityHeading: "Packages you still owe treatment on",
  liabilityNone: "No outstanding package liability",
  sessionsLeftShort: "{n} left",
  exportHeading: "Take your data",
  exportSubtitle: "Everything, any time, without asking us",
  exportCsv: "Download CSV",
  exportJson: "Download JSON",
  exportWhat: "Patients, appointments, packages, payments and refunds",
  exporting: "Preparing…",
  periodThisMonth: "This month",
  periodAllTime: "All time",
  moneyForbidden: "This account cannot see clinic finances.",
  // settings / team
  settings: "Settings",
  settingsSubtitle: "Your team and how this clinic is set up",
  teamHeading: "Team",
  teamSubtitle: "Everyone who can sign in to this clinic",
  addStaff: "Add someone",
  addStaffTitle: "Add someone to the team",
  fullName: "Full name",
  whatTheyDo: "What they do",
  createLogin: "Create their login",
  loginCreated: "Login created",
  loginCreatedHow:
    "Give them this password now — it is shown once and is not stored anywhere readable.",
  temporaryPassword: "Temporary password",
  copyIt: "Copy",
  copied: "Copied",
  doneAdding: "Done",
  emailTaken: "That email already has a login",
  removeFromTeam: "Remove from the team",
  removeConfirm:
    "They lose access immediately. Their past payments and notes stay on the record.",
  removeThem: "Remove",
  changeRole: "Change role",
  cannotRemoveSelf: "You cannot remove your own access",
  cannotDemoteLastOwner: "A clinic must keep at least one owner",
  onlyOwners: "Only an owner can manage the team.",
  clinicHeading: "This clinic",
  clinicNameLabel: "Clinic name",
  currencyLabel: "Currency",
  timezoneLabel: "Time zone",
  taxRateLabel: "Tax rate",
  taxLabelLabel: "What the tax is called",
  taxRateHint: "As a percentage. Leave at 0 where medical services are untaxed.",
  savedChanges: "Saved",
  saveChanges: "Save",
  settingsNeedMigration:
    "Currency, time zone and tax need migration 0004 applied before they can be saved.",
  you: "you",
  // clinical
  clinic: "Clinical",
  clinicalSubtitle: "Document a visit, track recovery",
  myDay: "My day",
  noPatientsToday: "No patients booked with you today",
  documentVisit: "Write up",
  documented: "Written up",
  notesFor: "Notes",
  newNote: "New note",
  copyLastVisit: "Copy from last visit",
  noPreviousVisit: "No previous note to copy",
  template: "Template",
  noTemplate: "Blank",
  subjective: "Subjective",
  objective: "Objective",
  assessment: "Assessment",
  planLabel: "Plan",
  subjectiveHint: "What the patient reports",
  objectiveHint: "What you found",
  assessmentHint: "Your clinical reasoning",
  planHint: "What happens next",
  saveNote: "Save the note",
  noteSaved: "Note saved",
  noteEmpty: "Write something in at least one section",
  visitCount: "{n} notes",
  noNotesYet: "No notes yet",
  measuresHeading: "Outcome measures",
  recordMeasure: "Record a measure",
  instrument: "Instrument",
  score: "Score",
  outOf: "out of {max}",
  improvedBy: "improved {n}",
  worsenedBy: "worse by {n}",
  noChange: "no change",
  firstReading: "first reading",
  readingsCount: "{n} readings",
  noMeasuresYet: "No measures recorded",
  saveMeasure: "Record it",
  measureSaved: "Recorded",
  scoreOutOfRange: "That score is outside the instrument's range",
  clinicalForbidden: "This account cannot see clinical records.",
  lowerIsBetter: "lower is better",
  higherIsBetter: "higher is better",
  redFlagsHeading: "Before you start",
  redFlagsHint:
    "Screening prompts, not a diagnosis. If any is present, consider referral — the decision is yours.",
  // selling a package
  sellPackage: "Sell a package",
  sellPackageSub: "Sessions paid for up front, used over time",
  sessionsInPackage: "Sessions",
  packagePrice: "Total price",
  perSessionWorks: "{amount} per session",
  expiresOptional: "Expires (optional)",
  depositNow: "Deposit taken now",
  depositHint: "Leave empty to invoice the whole amount later. Part-payment is fine.",
  sellIt: "Sell it",
  packageSold: "Package sold",
  sessionsOutOfRange: "A package holds between 1 and 200 sessions",
  walkInPrice: "Session price",
  walkInPriceHint:
    "What the patient is charged. Left at zero the session never shows up as unpaid.",
  packageCoversIt: "The package covers this session.",
  packageOutOfCredit:
    "That package only has {left} sessions left, and you asked for {asked}.",
  packageExhausted:
    "That package has no sessions left. Take a payment for this session, or sell a new package.",
  patientCredit: "Held on account",
  patientCreditHint: "Paid more than was owed — the patient's credit, not yours",
  // guided examination
  examine: "Examine",
  examTitle: "Examination",
  examSubtitle: "A structure to work through, not a diagnosis",
  pickRegion: "What are you examining?",
  screenFirst: "Screen first",
  screenFirstHint:
    "Ask these before anything else. Anything present is a reason to consider referral — the decision stays yours.",
  flagsClear: "Nothing flagged",
  flagsPresent: "{n} flagged — consider referral",
  continueAnyway: "Continue the examination",
  examines: "Examines",
  leftSide: "L",
  rightSide: "R",
  degrees: "degrees",
  present: "Present",
  absent: "Absent",
  notTested: "Not tested",
  bodyChart: "Where does it hurt?",
  frontView: "Front",
  backView: "Back",
  bodyChartHint: "Tap to mark. Tap a mark to remove it.",
  anatomyOf: "Region schematic",
  schematicNote:
    "A schematic, not an anatomical illustration — the structure the current step examines is highlighted.",
  stepOf: "Step {n} of {total}",
  nextStep: "Next",
  prevStep: "Back",
  finishExam: "Write it into the note",
  examSaved: "Examination saved to the note",
  nothingRecorded: "Record at least one finding first",
  reviewBeforeSaving: "Review before saving",
  stepsWord: "steps",
  objectiveGenerated: "This becomes the Objective section. Edit anything before saving.",
  portalGreeting: "Hello {name}",
  yourNextVisits: "Your next visits",
  noUpcomingVisits: "Nothing booked yet — call the clinic to arrange your next visit.",
  sessionsRemaining: "Sessions remaining",
  yourBalance: "Outstanding",
  yourExercises: "Your exercises",
  noExercisesYet: "Your therapist hasn't set any exercises yet.",
  setsReps: "{sets} × {reps}",
  holdFor: "hold {n}s",
  watchIt: "Watch",
  portalNotFound: "This link isn't valid. Ask the clinic for a new one.",
  portalRevoked: "This link has been withdrawn. Ask the clinic for a new one.",
  portalExpired: "This link has expired. Ask the clinic for a new one.",
  portalPrivacy:
    "This page shows only your appointments, sessions and exercises. Don't forward the link — it opens your record.",
  callClinic: "Call the clinic",
  exercisesHeading: "Home exercises",
  addExercise: "Add an exercise",
  exerciseName: "Exercise",
  exerciseInstructions: "How to do it",
  exerciseInstructionsHint: "Write it for the patient, in their words.",
  setsLabel: "Sets",
  repsLabel: "Reps",
  holdLabel: "Hold (seconds)",
  frequencyLabel: "How often",
  frequencyPlaceholder: "twice a day",
  videoLabel: "Video link (optional)",
  saveExercise: "Prescribe it",
  retireExercise: "Retire",
  retired: "Retired",
  patientLink: "Patient link",
  patientLinkSub: "A link they open from WhatsApp — no password",
  createLink: "Create a link",
  linkCreated: "Link created",
  linkOnce:
    "Copy it now — only its fingerprint is stored, so it cannot be shown again.",
  shareOnWhatsApp: "Send on WhatsApp",
  copyLink: "Copy the link",
  revokeLink: "Withdraw",
  linkRevoked: "Withdrawn",
  activeLinks: "{n} active",
  neverOpened: "never opened",
  lastOpened: "opened {date}",
  whatsAppMessage:
    "Hello {name}, this is your page at {clinic} — your appointments and home exercises:",

  // receipts
  receipt: "Receipt",
  receiptNo: "Receipt {n}",
  issueReceipt: "Receipt",
  receiptIssued: "Receipt {n} issued",
  receiptFor: "Receipt for {name}",
  patientLabel: "Patient",
  dateLabel: "Date",
  methodLabel: "Method",
  byLabel: "Taken by",
  subtotalLabel: "Subtotal",
  taxOnReceipt: "{label} at {rate}%",
  totalPaid: "Total paid",
  paidBy: "Paid by {method}",
  issuedOn: "Issued {date}",
  issuedBy: "Issued by {name}",
  printReceipt: "Print",
  notATaxInvoice:
    "Receipt for payment received. Not a statutory tax invoice.",
  receiptNotFound: "No such receipt in this clinic.",
  receiptsForbidden: "This account cannot issue receipts.",

  // consent (PDPL)
  consentHeading: "Consent",
  consentSub: "Explicit and per purpose, as Law 151/2020 requires",
  purpose_treatment: "Assessment and treatment",
  purpose_records_storage: "Keeping the clinical record",
  purpose_whatsapp_messaging: "Contact on WhatsApp",
  purpose_insurance_disclosure: "Disclosure to an insurer",
  method_in_person_signature: "Signed in person",
  method_portal: "Agreed on their own link",
  method_verbal_witnessed: "Verbal, witnessed",
  consentGivenOn: "given {date}",
  consentNotGiven: "not given",
  consentWithdrawnOn: "withdrawn {date}",
  recordConsent: "Record",
  withdrawConsent: "Withdraw",
  consentWordingLabel: "What the patient was told",
  consentWordingHint:
    "Stored word for word. Consent is only informed if this is recoverable later.",
  consentMethodLabel: "How it was given",
  consentSaved: "Recorded",
  consentWordingRequired: "Write what the patient was told.",
} as const;

type Key = keyof typeof en;

const ar: Record<Key, string> = {
  appName: "Clinic OS",
  appTagline: "إدارة عيادات العلاج الطبيعي",

  signInTitle: "Clinic OS",
  signInSubtitle: "سجّل دخولك تشوف يوم العيادة",
  email: "البريد الإلكتروني",
  password: "كلمة السر",
  signIn: "دخول",
  badCredentials: "الإيميل أو كلمة السر غلط",
  signOut: "خروج",

  receptionDay: "الاستقبال",
  searchTheDay: "ابحث في اليوم",
  liveUpdating: "مباشر",
  darkMode: "الوضع الليلي",
  lightMode: "الوضع النهاري",
  notInAnyClinic: "الحساب ده مش مربوط بأي عيادة بعد. كلّم صاحب العيادة يضيفك.",
  mustSignIn: "لازم تسجل الدخول أولاً.",

  roleOwner: "المالك",
  roleReception: "استقبال",
  roleTherapist: "أخصائي",
  roleAccountant: "محاسب",
  rolePlatformAdmin: "أدمن المنصة",

  waiting: "في الانتظار",
  ofAppointmentsToday: "من {n} موعد النهاردة",
  finished: "خلصوا",
  noShows: "غابوا",
  owedByPatients: "مستحق على المرضى",
  acrossNPatients: "على {n} مرضى",

  bandWaiting: "في الانتظار",
  bandDone: "خلصوا",
  queueEmpty: "مفيش حد مستني — الطابور فاضي",
  noSearchResults: "مفيش نتيجة للبحث ده",
  nobodyFinishedYet: "لسه محدش خلص النهاردة",
  filterPlaceholder: "فلتر بالاسم أو التليفون",
  addWalkIn: "+ حالة مفاجئة",

  arrived: "وصل",
  noShow: "غاب",
  didNotAttend: "غاب",
  takePayment: "اقبض",
  refund: "استرجاع",
  onTime: "في الميعاد",
  waitingMinutes: "مستني {n}د",
  dueInMinutes: "بعد {n}د",
  owesAmount: "عليه {amount}",
  missesRate: "يغيب {n}٪ من مواعيده",

  paymentTitle: "قبض فلوس",
  due: "مستحق",
  packageOptional: "الباقة (اختياري)",
  noPackageSingleSession: "بدون باقة — جلسة فردية",
  packageOf: "باقة {n} جلسة",
  sessionsLeft: "فاضل {n}",
  paymentGoesToPackage: "الدفعة هتتحسب على الباقة، مش على جلسة النهاردة.",
  method: "وسيلة الدفع",
  amount: "المبلغ",
  cash: "كاش",
  card: "بطاقة",
  wallet: "محفظة إلكترونية",
  addAnotherMethod: "+ وسيلة دفع تانية (تقسيم المبلغ)",
  removeMethod: "شيل وسيلة الدفع دي",
  total: "الإجمالي",
  cancel: "إلغاء",
  take: "اقبض",
  enterAnAmount: "اكتب مبلغ أكبر من صفر",

  refundTitle: "استرجاع فلوس",
  payment: "الدفعة",
  refundAmount: "المبلغ المسترجع",
  reason: "السبب",
  reasonPlaceholder: "مثلاً: إلغاء جلسة بعد الدفع",
  refundIt: "ارجع الفلوس",
  noPaymentsYet: "مفيش دفعات مسجلة للمريض ده",
  maxRefundableBefore: "أقصى مبلغ",
  maxRefundableAfter: " — الداتابيز نفسها بترفض أي استرجاع أكبر من الدفعة.",
  pickAPayment: "اختار الدفعة المطلوب استرجاعها",
  amountAboveZero: "المبلغ لازم يكون أكبر من صفر",
  reasonRequired: "اكتب سبب الاسترجاع — بيتسجّل في الدفاتر",

  walkInTitle: "حالة مفاجئة",
  walkInSubtitle: "بتتحجز من الوقت الحالي",
  existingPatient: "مريض موجود؟",
  searchByNameOrPhone: "ابحث بالاسم أو رقم التليفون",
  orNewPatient: "أو مريض جديد",
  name: "الاسم",
  phone: "رقم التليفون",
  change: "غيّر",
  consentLabel:
    "المريض موافق على معالجة بياناته الصحية. مطلوب قانونًا — البيانات الصحية بيانات حساسة تحت قانون ١٥١ لسنة ٢٠٢٠.",
  therapist: "الأخصائي",
  noTherapists: "مفيش أخصائيين",
  sessionMinutes: "مدة الجلسة (دقيقة)",
  underPackage: "تحت باقة؟",
  noSingleSession: "لأ — جلسة فردية",
  addToQueue: "ضيفه للطابور",
  pickPatientOrEnterNew: "اختار مريض موجود أو اكتب اسم ورقم مريض جديد",
  consentRequired: "لازم موافقة المريض على معالجة بياناته الصحية",
  pickTherapist: "اختار أخصائي",
  durationAboveZero: "مدة الجلسة لازم تكون أكبر من صفر",
  therapistBusy: "الأخصائي محجوز في الوقت ده",

  leakingTitle: "فلوس سايبة",
  leakingSubtitle: "جلسات اتعملت ومحدش دفع تمنها",
  nothingLeaking: "كل الجلسات مدفوعة.",
  sessionOn: "جلسة {date}",
  totalOwed: "الإجمالي المستحق",
  stalePackagesTitle: "باقات واقفة",
  stalePackagesSubtitle:
    "مدفوعة وجلساتها مش بتتستهلك — أول إشارة إن المريض هيسيب",
  lastSessionOn: "آخر جلسة {date} · فاضل {n}",
  notStartedYet: "لسه مابدأتش",

  adminTitle: "المنصة",
  adminSubtitle: "كل العيادات على النظام",
  adminForbidden: "الحساب ده مش أدمن منصة. مفيش حاجة هنا متاحة له.",
  adminNotConfigured:
    "مفيش أدمن منصة معرّف. حدّد PLATFORM_ADMIN_EMAILS في بيئة السيرفر.",
  clinics: "العيادات",
  staff: "الفريق",
  patients: "المرضى",
  appointments: "المواعيد",
  collected: "المحصّل",
  outstanding: "المستحق",
  refunded: "المسترجع",
  clinicName: "العيادة",
  activity: "مين عمل إيه",
  activitySubtitle: "الأحدث الأول، من كل العيادات",
  noActivity: "لسه مفيش حاجة حصلت",
  actionTookPayment: "قبض {amount}",
  actionRefunded: "رجّع {amount}",
  actionRegisteredPatient: "سجّل مريض",
  actionBookedAppointment: "حجز موعد",
  actionSoldPackage: "باع باقة {n} جلسة",
  phiNotice:
    "أسماء المرضى والملاحظات الإكلينيكية مش معروضة هنا عن قصد. أدمن المنصة يشوف الشغل ماشي إزاي، مش مين بيتعالج من إيه.",
  backToClinic: "رجوع للعيادة",
  unknownUser: "غير معروف",
  noClinics: "مفيش عيادات",
  schedule: "الجدول",
  scheduleSubtitle: "احجز مقدماً، انقل، الغِ",
  weekOf: "أسبوع {date}",
  today: "النهاردة",
  prevWeek: "الأسبوع اللي فات",
  nextWeek: "الأسبوع الجاي",
  allTherapists: "كل الأخصائيين",
  book: "احجز",
  bookSession: "احجز جلسة",
  bookPlanOfCare: "احجز خطة علاج",
  oneSession: "جلسة واحدة",
  planOfCare: "خطة علاج",
  date: "التاريخ",
  time: "الوقت",
  sessions: "الجلسات",
  repeatOn: "تتكرر يوم",
  pricePerSession: "سعر الجلسة",
  priceHint: "سيبه صفر لو الجلسة تحت باقة.",
  checkSlots: "افحص المواعيد",
  slotsClear: "كل الـ {n} مواعيد فاضية",
  slotsClash: "{n} من {total} مواعيد فيهم تعارض",
  clashesWith: "متعارض مع {name}",
  clashesWithSomeone: "متعارض مع حجز تاني",
  bookAnyway: "احجز الـ {n} الفاضيين",
  bookAll: "احجز {n} جلسة",
  booked: "اتحجزت",
  bookedNOfM: "اتحجز {n} من {total}",
  noneBooked: "محجزش أي حاجة",
  moveTo: "انقل لـ",
  moveIt: "انقل",
  cancelSession: "الغِ الجلسة دي",
  cancelIt: "الغِ الجلسة",
  cancelWarning:
    "الموعد يفضى، ولو الجلسة كانت متسجلة حضور الباقة بترجع جلستها.",
  cancelled: "ملغية",
  attended: "حضر",
  bookedStatus: "محجوز",
  nothingThisWeek: "مفيش حجوزات الأسبوع ده",
  noPatientPicked: "اختار مريض الأول",
  badDateOrTime: "التاريخ أو الوقت مش صحيح",
  tooManySessions: "خطة العلاج أقصاها ٦٠ جلسة",
  pickWeekdays: "اختار يوم واحد على الأقل للتكرار",
  sat: "السبت",
  sun: "الحد",
  mon: "الاتنين",
  tue: "التلات",
  wed: "الأربع",
  thu: "الخميس",
  fri: "الجمعة",
  patientRecord: "المريض",
  backToReception: "رجوع لليوم",
  registered: "مسجّل",
  consentOn: "الموافقة مسجّلة {date}",
  consentMissing: "مفيش موافقة مسجّلة",
  consentMissingWhy:
    "البيانات الصحية حساسة تحت قانون ١٥١ لسنة ٢٠٢٠. سجّل الموافقة قبل إضافة أي بيانات إكلينيكية.",
  lastSeen: "آخر زيارة",
  neverSeen: "لسه مجاش",
  totalSessions: "جلسات حضرها",
  missedSessions: "غاب",
  lifetimeValue: "دفع لحد الآن",
  currentlyOwes: "عليه حالياً",
  packagesHeading: "الباقات",
  noPackages: "مفيش باقات",
  packageProgress: "استهلك {used} من {total}",
  expiredOn: "انتهت {date}",
  expiresOn: "تنتهي {date}",
  paidOff: "مدفوعة بالكامل",
  stillOwing: "باقي {amount}",
  historyHeading: "تاريخ الزيارات",
  noHistory: "مفيش زيارات",
  paymentsHeading: "الدفعات",
  noPaymentsRecorded: "مفيش دفعات",
  upcomingHeading: "القادم",
  noUpcoming: "مفيش حجوزات",
  patientNotFound: "مفيش مريض بالاسم ده في العيادة",
  viewRecord: "افتح الملف",
  findPatient: "ابحث عن مريض",
  findPatientHint: "بحث في كل العيادة، مش جدول النهاردة بس",
  searchResults: "{n} نتيجة",
  noMatches: "مفيش حد بالاسم ده",
  typeToSearch: "اكتب اسم أو رقم تليفون",
  owes: "عليه",
  progress: "التقدم",
  percentOf: "{value} من {max}",
  finance: "الفلوس",
  financeSubtitle: "اللي كسبته، واللي ليك، واللي عليك علاج",
  leakHeadline: "{n} جلسة اتعملت من غير دفع",
  leakNone: "كل جلسة اتعملت اتدفعت.",
  leakTotal: "مش محصّل",
  chaseIt: "تابع",
  earned: "مكتسب",
  earnedHint: "علاج اتقدّم فعلاً",
  deferred: "محتفظ بيه لعلاج مستحق",
  deferredHint: "مدفوع ولسه ماتقدّمش — ده التزام، مش ربح",
  receivable: "لك",
  receivableHint: "اتقدّم ومادُفعش",
  collectedCash: "المحصّل",
  collectedHint: "اللي دخل الخزنة، بعد خصم الاسترجاع",
  ofCashIsNotYours: "{pct}٪ من فلوسك لسه مش من حقك تصرفها",
  liabilityHeading: "باقات لسه عليك علاجها",
  liabilityNone: "مفيش التزام باقات",
  sessionsLeftShort: "فاضل {n}",
  exportHeading: "خُد بياناتك",
  exportSubtitle: "كل حاجة، في أي وقت، من غير ما تسألنا",
  exportCsv: "نزّل CSV",
  exportJson: "نزّل JSON",
  exportWhat: "المرضى والمواعيد والباقات والدفعات والاسترجاعات",
  exporting: "بيتجهّز…",
  periodThisMonth: "الشهر ده",
  periodAllTime: "من الأول",
  moneyForbidden: "الحساب ده مايشوفش ماليات العيادة.",
  settings: "الإعدادات",
  settingsSubtitle: "فريقك وإعدادات العيادة",
  teamHeading: "الفريق",
  teamSubtitle: "كل اللي يقدر يدخل على العيادة",
  addStaff: "ضيف حد",
  addStaffTitle: "ضيف حد للفريق",
  fullName: "الاسم كامل",
  whatTheyDo: "بيعمل إيه",
  createLogin: "اعمل له حساب",
  loginCreated: "الحساب اتعمل",
  loginCreatedHow:
    "اعطيه كلمة السر دي دلوقتي — بتتعرض مرة واحدة ومش متسجلة في أي مكان يتقرا.",
  temporaryPassword: "كلمة سر مؤقتة",
  copyIt: "انسخ",
  copied: "اتنسخت",
  doneAdding: "خلصت",
  emailTaken: "الإيميل ده له حساب بالفعل",
  removeFromTeam: "شيله من الفريق",
  removeConfirm:
    "هيفقد الوصول فوراً. دفعاته وملاحظاته القديمة تفضل في السجل.",
  removeThem: "شيله",
  changeRole: "غيّر الدور",
  cannotRemoveSelf: "مش ممكن تشيل وصولك بنفسك",
  cannotDemoteLastOwner: "العيادة لازم يفضل فيها مالك واحد على الأقل",
  onlyOwners: "المالك بس هو اللي يدير الفريق.",
  clinicHeading: "العيادة",
  clinicNameLabel: "اسم العيادة",
  currencyLabel: "العملة",
  timezoneLabel: "المنطقة الزمنية",
  taxRateLabel: "نسبة الضريبة",
  taxLabelLabel: "اسم الضريبة",
  taxRateHint: "كنسبة مئوية. سيبها صفر لو الخدمات الطبية غير خاضعة للضريبة.",
  savedChanges: "اتسجّل",
  saveChanges: "احفظ",
  settingsNeedMigration:
    "العملة والتوقيت والضريبة محتاجين migration 0004 يتطبق قبل ما يتحفظوا.",
  you: "إنت",
  clinic: "الإكلينيكي",
  clinicalSubtitle: "وثّق الجلسة، تابع التحسّن",
  myDay: "يومي",
  noPatientsToday: "مفيش مرضى محجوزين معاك النهاردة",
  documentVisit: "وثّق",
  documented: "متوثّقة",
  notesFor: "الملاحظات",
  newNote: "ملاحظة جديدة",
  copyLastVisit: "انسخ من آخر جلسة",
  noPreviousVisit: "مفيش ملاحظة سابقة تتنسخ",
  template: "قالب",
  noTemplate: "فاضي",
  subjective: "الشكوى",
  objective: "الفحص",
  assessment: "التقييم",
  planLabel: "الخطة",
  subjectiveHint: "اللي المريض بيقوله",
  objectiveHint: "اللي إنت لقيته",
  assessmentHint: "استنتاجك الإكلينيكي",
  planHint: "الخطوة الجاية",
  saveNote: "احفظ الملاحظة",
  noteSaved: "اتحفظت",
  noteEmpty: "اكتب حاجة في قسم واحد على الأقل",
  visitCount: "{n} ملاحظة",
  noNotesYet: "مفيش ملاحظات",
  measuresHeading: "مقاييس النتائج",
  recordMeasure: "سجّل قياس",
  instrument: "المقياس",
  score: "الدرجة",
  outOf: "من {max}",
  improvedBy: "اتحسّن {n}",
  worsenedBy: "زاد {n}",
  noChange: "مفيش تغيير",
  firstReading: "أول قياس",
  readingsCount: "{n} قياسات",
  noMeasuresYet: "مفيش قياسات",
  saveMeasure: "سجّل",
  measureSaved: "اتسجّل",
  scoreOutOfRange: "الدرجة خارج نطاق المقياس",
  clinicalForbidden: "الحساب ده مايشوفش الملفات الإكلينيكية.",
  lowerIsBetter: "الأقل أحسن",
  higherIsBetter: "الأعلى أحسن",
  redFlagsHeading: "قبل ما تبدأ",
  redFlagsHint:
    "أسئلة فحص، مش تشخيص. لو أي واحدة موجودة، فكّر في التحويل — القرار قرارك.",
  sellPackage: "بيع باقة",
  sellPackageSub: "جلسات مدفوعة مقدماً، تتستهلك على مدى الوقت",
  sessionsInPackage: "عدد الجلسات",
  packagePrice: "السعر الإجمالي",
  perSessionWorks: "{amount} للجلسة",
  expiresOptional: "تنتهي في (اختياري)",
  depositNow: "مقدم دلوقتي",
  depositHint: "سيبه فاضي لو الحساب هيتحصّل بعدين. الدفع الجزئي مقبول.",
  sellIt: "بيع",
  packageSold: "الباقة اتباعت",
  sessionsOutOfRange: "الباقة من جلسة لـ٢٠٠ جلسة",
  walkInPrice: "سعر الجلسة",
  walkInPriceHint:
    "المبلغ المستحق على المريض. لو سيبته صفر، الجلسة عمرها ما تظهر كغير مدفوعة.",
  packageCoversIt: "الباقة بتغطي الجلسة دي.",
  packageOutOfCredit:
    "الباقة دي فاضل فيها {left} جلسات بس، وإنت طلبت {asked}.",
  packageExhausted:
    "الباقة دي خلصت. اقبض تمن الجلسة دي، أو بيع باقة جديدة.",
  patientCredit: "محتفظ بيه للمريض",
  patientCreditHint: "دفع أكتر من المستحق — رصيد للمريض، مش لك",
  examine: "افحص",
  examTitle: "الفحص",
  examSubtitle: "هيكل تمشي عليه، مش تشخيص",
  pickRegion: "بتفحص إيه؟",
  screenFirst: "افحص ده الأول",
  screenFirstHint:
    "اسأل دي قبل أي حاجة. أي واحدة موجودة سبب تفكّر في التحويل — القرار يفضل قرارك.",
  flagsClear: "مفيش حاجة",
  flagsPresent: "{n} موجودة — فكّر في التحويل",
  continueAnyway: "كمّل الفحص",
  examines: "بيفحص",
  leftSide: "يسار",
  rightSide: "يمين",
  degrees: "درجة",
  present: "موجود",
  absent: "غير موجود",
  notTested: "ماتفحصش",
  bodyChart: "بيوجعه فين؟",
  frontView: "أمام",
  backView: "خلف",
  bodyChartHint: "دوس تحدّد. دوس على العلامة تشيلها.",
  anatomyOf: "رسم المنطقة",
  schematicNote:
    "رسم توضيحي، مش صورة تشريحية — المنطقة اللي الخطوة الحالية بتفحصها مضيّاة.",
  stepOf: "خطوة {n} من {total}",
  nextStep: "التالي",
  prevStep: "السابق",
  finishExam: "اكتبه في الملاحظة",
  examSaved: "الفحص اتحفظ في الملاحظة",
  nothingRecorded: "سجّل نتيجة واحدة على الأقل",
  reviewBeforeSaving: "راجع قبل الحفظ",
  stepsWord: "خطوة",
  objectiveGenerated: "ده بيبقى قسم الفحص. عدّل أي حاجة قبل الحفظ.",
  portalGreeting: "أهلاً {name}",
  yourNextVisits: "مواعيدك الجاية",
  noUpcomingVisits: "مفيش موعد محجوز — كلّم العيادة تحدد الجلسة الجاية.",
  sessionsRemaining: "جلسات فاضلة",
  yourBalance: "المستحق",
  yourExercises: "تمارينك",
  noExercisesYet: "الأخصائي لسه محددش تمارين.",
  setsReps: "{sets} × {reps}",
  holdFor: "ثبّت {n} ثانية",
  watchIt: "شوف الفيديو",
  portalNotFound: "اللينك ده مش صالح. اطلب من العيادة لينك جديد.",
  portalRevoked: "اللينك ده اتسحب. اطلب من العيادة لينك جديد.",
  portalExpired: "اللينك ده انتهى. اطلب من العيادة لينك جديد.",
  portalPrivacy:
    "الصفحة دي بتوريك مواعيدك وجلساتك وتمارينك بس. متبعتش اللينك لحد — بيفتح ملفك.",
  callClinic: "اتصل بالعيادة",

  exercisesHeading: "تمارين البيت",
  addExercise: "ضيف تمرين",
  exerciseName: "التمرين",
  exerciseInstructions: "بيتعمل إزاي",
  exerciseInstructionsHint: "اكتبه للمريض، بكلامه.",
  setsLabel: "مجموعات",
  repsLabel: "عدات",
  holdLabel: "تثبيت (ثانية)",
  frequencyLabel: "كل قد إيه",
  frequencyPlaceholder: "مرتين في اليوم",
  videoLabel: "لينك فيديو (اختياري)",
  saveExercise: "اكتب التمرين",
  retireExercise: "أوقفه",
  retired: "موقوف",
  patientLink: "لينك المريض",
  patientLinkSub: "لينك يفتحه من واتساب — بدون باسورد",
  createLink: "اعمل لينك",
  linkCreated: "اللينك اتعمل",
  linkOnce: "انسخه دلوقتي — بصمته بس هي المحفوظة، فمش هيتعرض تاني.",
  shareOnWhatsApp: "ابعت على واتساب",
  copyLink: "انسخ اللينك",
  revokeLink: "اسحبه",
  linkRevoked: "اتسحب",
  activeLinks: "{n} فعّال",
  neverOpened: "مافتحوش",
  lastOpened: "اتفتح {date}",
  whatsAppMessage:
    "أهلاً {name}، دي صفحتك في {clinic} — مواعيدك وتمارين البيت:",

  receipt: "إيصال",
  receiptNo: "إيصال {n}",
  issueReceipt: "إيصال",
  receiptIssued: "اتطبع إيصال {n}",
  receiptFor: "إيصال لـ {name}",
  patientLabel: "المريض",
  dateLabel: "التاريخ",
  methodLabel: "طريقة الدفع",
  byLabel: "استلمه",
  subtotalLabel: "المبلغ قبل الضريبة",
  taxOnReceipt: "{label} بنسبة {rate}%",
  totalPaid: "المدفوع",
  paidBy: "الدفع {method}",
  issuedOn: "اتحرر {date}",
  issuedBy: "حرّره {name}",
  printReceipt: "اطبع",
  notATaxInvoice: "إيصال باستلام مبلغ. مش فاتورة ضريبية رسمية.",
  receiptNotFound: "مافيش إيصال بالرقم ده في العيادة.",
  receiptsForbidden: "الحساب ده مش من حقه يحرّر إيصالات.",

  consentHeading: "الموافقة",
  consentSub: "صريحة ولكل غرض على حدة، زي ما قانون ١٥١/٢٠٢٠ بيطلب",
  purpose_treatment: "الفحص والعلاج",
  purpose_records_storage: "الاحتفاظ بالملف الطبي",
  purpose_whatsapp_messaging: "التواصل على واتساب",
  purpose_insurance_disclosure: "الإفصاح لشركة تأمين",
  method_in_person_signature: "توقيع حضوري",
  method_portal: "وافق من اللينك بتاعه",
  method_verbal_witnessed: "شفهي بحضور شاهد",
  consentGivenOn: "اتوافق {date}",
  consentNotGiven: "مش موجودة",
  consentWithdrawnOn: "اتسحبت {date}",
  recordConsent: "سجّل",
  withdrawConsent: "اسحب",
  consentWordingLabel: "اللي اتقال للمريض",
  consentWordingHint:
    "بيتخزّن بالحرف. الموافقة مابتكونش مستنيرة غير لو الكلام ده يرجع يتقرا بعدين.",
  consentMethodLabel: "إزاي اتوافق",
  consentSaved: "اتسجّلت",
  consentWordingRequired: "اكتب اللي اتقال للمريض.",
};

const TABLE = LOCALE === "ar" ? ar : en;

export function t(key: Key, vars?: Record<string, string | number>) {
  const raw: string = TABLE[key];
  if (!vars) return raw;
  return raw.replace(/\{(\w+)\}/g, (_, k) =>
    String(vars[k] ?? `{${k}}`)
  );
}
